-- Create image_details_for_ai_generation table
CREATE TABLE IF NOT EXISTS "image_details_for_ai_generation" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"character_id" uuid NOT NULL,
	"physical_appearance" text,
	"clothing" text,
	"accessories" text,
	"facial" text,
	"hair" text,
	"eyes" text,
	"build" text,
	"distinguishing_marks" text,
	"mood" text,
	"expression" text,
	"pose" text,
	"environment" text,
	"lighting" text,
	"color_palette" text,
	"art_style" text,
	"composition" text,
	"background" text,
	"atmosphere" text,
	"magical_elements" text,
	"cultural_elements" text,
	"temporal_context" text,
	"special_effects" text,
	"artistic_influences" text,
	"detail_level" varchar(50) DEFAULT 'high',
	"generation_prompt" text,
	"negative_prompt" text,
	"aspect_ratio" varchar(20) DEFAULT '1:1',
	"scale" varchar(50) DEFAULT '5',
	"quality_level" varchar(50) DEFAULT 'hd',
	"style_references" text,
	"mood_keywords" text,
	"technical_parameters" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "image_details_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE cascade,
	CONSTRAINT "image_details_character_id_unique" UNIQUE("character_id")
);

-- Create index on character_id for faster queries
CREATE INDEX IF NOT EXISTS "image_details_character_id_idx" ON "image_details_for_ai_generation"("character_id");
